
settings:
  pr_comment_report:
    enabled: True
    delete_previous: True
    show_empty_sections: False
    show_message: True
    show_details: True
    show_successful: False
checks:
  branch_name:
    pattern: ^TX-[0-9]+\-[\w\d\-]+$
    pattern_descr: Branch name must start with the Jira ticket ID and include lowercase characters, digits and dashes, e.g. `TX-999-sync-translations`
    failure_level: warning
  pr_title:
    pattern: ^TX-[0-9]+ [A-Z].+$
    pattern_descr: PR title must start with the Jira ticket ID, followed by a space and a capitalized word, e.g. `TX-9999 Sync translations to Transifex`
    failure_level: warning
  pr_body_checklist:
    failure_level: error
  pr_body_excludes:
    patterns:
      - TX-XXXX
    failure_level: error
  pr_body_includes:
    patterns:
      - Problem and/or solution
      - How to test
      - Reviewer checklist
    failure_level: error
  commit_message:
    subject:
      min_length: 10
      max_length: 50
      pattern: ^[A-Z].+(?<!\.)$
      pattern_descr: Commit message subject must start with a capital letter and must not finish with a dot
    body:
      max_line_length: 72
      smart_require:
        min_changes: 100
        min_body_lines: 1
    failure_level: error
